# Generated by Django 3.2.5 on 2021-12-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_iscomplted_todo_iscompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='slug',
        ),
    ]
